name: Go
on:
  push:
    tags:
      - "*"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: make
      
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v0.2.2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        title: rss-godler ${{ github.ref }}
        draft: false
        prerelease: false
        files: |
          rss-godler
          rss-godler.exe
          rss-godler_darwin
